### ISSUE TITLE
error throwing in the back causes the server to crash and exit

### ISSUE THREAD

**Issue by sou-c** [dsi-icl/optimise-core#115]
![screen shot 2018-07-17 at 12 05 18](https://user-images.githubusercontent.com/35537528/42813723-d4505896-89b9-11e8-8985-fa60504251b3.png)

try: 
{{url}}/patients/c?getOnly=DemographicData

**Comment by sou-c** [comment]
Also, is it so that I can't just fetch a single key in the patientProfile anymore?

**Comment by sou-c** [comment]
![screen shot 2018-07-19 at 14 42 13](https://user-images.githubusercontent.com/35537528/42946090-f9383d28-8b61-11e8-8ecb-094ccbdcada3.png)


This clearly is sending plain text back..as the front end is expecting all backend respon to be json this will cause the front to crash

**Comment by fguitton** [comment]
I believe this is now addressed, please confirm
