### ISSUE TITLE
export CDISC

### ISSUE THREAD

**Issue by sou-c** [dsi-icl/optimise-core#12]
write function (functions) and API that transform the current data model into CDISC compliant format

**Comment by sou-c** [comment]
we should think about whether we provide a one-off http streaming-data-to-client type of download or create a job and write to local file and provide a link to the client

**Comment by fguitton** [comment]
@epissari How is this progressing ?

**Comment by epissari** [comment]
Just pushed branch `implementing-export`

**Comment by fguitton** [comment]
@epissari How is this progressing ? I am not seeing **anything** arriving on the branch. Appart from two commits to an SQL file. Is this working now ? Can we close the issue ? 12 days for an exports API is way too long, deadlines are coming fast !

**Comment by epissari** [comment]
@fguitton This is working for demographic data- the user can download a csv of this information. Please see commit a2647ce6ad9f309fdd8523fd61ec2f7fbc139a75. I am making changes to the database after yesterday's meeting in branch `db-modifications` and export depends on that.

**Comment by epissari** [comment]
Basic export functionality in commit 86d9be143af213911e65b112d53f46fc7b93edc7 (initial architecture). Need to refactor export controller.
