### ISSUE TITLE
/patients/chon?getOnly=DemographicData doesn't work

### ISSUE THREAD

**Issue by sou-c** [dsi-icl/optimise-core#125]
Is there a way to only get a specific part of the patient's profile? or is this function removed

**Comment by sou-c** [comment]
![screen shot 2018-07-19 at 14 47 03](https://user-images.githubusercontent.com/35537528/42946404-aaa9533a-8b62-11e8-9b78-91723ebdfb81.png)

as of commit 69ce6f274c2297cc31375984a0b7f9d7f573f2e9

Because this returning a promise and there is no then() to catch it the server stalls

**Comment by fguitton** [comment]
This should be addressed in 7046931e9bc55630ddea3ae48c7a463ae9cacc84, please confirm
