### ISSUE TITLE
UNIQUE fail from deleted

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise-core#18]
It's possible to create a user with the same username. The problem is that it can be patched but there's another issue linked to it.
If for example we have a user with a username "user1" set as delete, technically we could add a user with the same username. But the fact that the delete column can be null it's not possible to add it to a UNIQUE constrain. We can go on multiple solutions :
1 - An homemade verification before insert (i.e. Checking in the DB if the entry is already present and if deleted allow the insert or cancel it if not).
2 - Changing all the deleted field in the schema of the database to NOT NULL and allow the UNIQUE constrain.
3 - Adding TRIGGER in the database to see if the entry can be inserted or not.

**Comment by Radiateurs** [comment]
This thread is giving some ideas
https://stackoverflow.com/questions/22699409/sqlite-null-and-unique

**Comment by Radiateurs** [comment]
Another solution that I will test :
https://www.techonthenet.com/sqlite/unique.php

**Comment by Radiateurs** [comment]
Another solution on this website that is pretty much the same as one of the solution from the first link: 
https://ericsink.com/mssql_mobile/unique_null.html

**Comment by sou-c** [comment]
i personally think we should revert back to where we set deleted=0..and let the database do the logic for us..others please contribute

**Comment by Radiateurs** [comment]
Or we could create a table called DELETED_USER and everytime we create a user we add him in it. 
The only thing that will be dangerous will be the references in the other table

**Comment by sou-c** [comment]
i don't think it's a good idea to overcomplicate things

**Comment by sou-c** [comment]
if we do another table, we would have to have a record EVERY user, patient, test, visit, data, CE, treatment deletion..it's impractical

**Comment by Radiateurs** [comment]
I do agree with you. Just giving other ideas

**Comment by Radiateurs** [comment]
@fguitton Any ideas on the subject ?

**Comment by fguitton** [comment]
For other projects we have used a `deleted` column which contains a string `-` by default and when the item has been deleted contains a string concatenation of the ID of the item and the ID of the user who deleted it `[id_item]+[is_user]`, then we have a composite unique constraint on three fields : `id`/`name`/`deleted`.


id | tag | removed | creation | modification
--- | --- | --- | --- | ---
`1293` | `00392837` | `-` | `03/02/2016 12:34:45` | `03/02/2016 12:34:45`
`1837` | `00359283` | `-` | `15/02/2016 09:34:37` | `15/02/2016 09:34:37`
`4092` | `00359283` | `4092+3` | `17/03/2016 15:21:38` | `21/11/2017 08:21:56`
`5093` | `00318475` | `5093+3` | `24/08/2017 16:03:59` | `21/11/2017 08:22:34`
`7837` | `00481973` | `7837+5` | `03/09/2017 21:21:35` | `30/01/2018 17:45:21`

**Comment by Radiateurs** [comment]
Then we should go on Chon's idea.
