### ISSUE TITLE
/api/users architectural issue

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise-core#3]
The creation / deletion / modification of a user is made on /api/users by an admin.
Maybe for architecture purpose we should change it to /internalapi/users ?

**Comment by fguitton** [comment]
What is the difference made here between /api and /internalapi ?

**Comment by Radiateurs** [comment]
@fguitton As far as I understand, /api is related to patients data purpose.
/internalapi is related to users such as login and logout.
Since /api/users lists the users, Inthink or should be in /internalapi
