### ISSUE TITLE
Method returns are inconsistent

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise-core#39]
There are multiple problems where return types are totally inconsistent.
Example with :

https://github.com/dsi-icl/optimise-core/blob/f2d79618be4f8ff3d8f41b471d648cf15a10e591/src/utils/basic-utils.js#L10-L25

The method returns a Boolean or a string. This is heavily error prone.
An audit of all functions should be carried out.

**Comment by sou-c** [comment]
it's used in a if(validateAndFormatDate()) which evaluates to true or false

**Comment by fguitton** [comment]
I understand that, but the function should be return a type-compatible value. There are many examples of problem functions throughout the code. Validation and formatting are two very different actions. In this case they should be split.

There also exist native implementation of Date validation with `Date.parse()`

For this particular example however, as we discussed a couple of days ago, dates should be stored in database in full localized format.

**Comment by Radiateurs** [comment]
[UPDATE] Mainly patched in 661718596db73a9575a8f5f9eefd47e90fa958fc
