### ISSUE TITLE
console.log() hell needs to be addressed

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise-core#40]
Error propagation should be done by leveraging JSON responses. The use of `process.env.NODE_ENV` should be considered if we effectively want to filter out certain error debug data. The best way would be to implement an ErrorHelper class to handle processing and filtering of error messages

**Comment by Radiateurs** [comment]
[Update] Partially fixed in 661718596db73a9575a8f5f9eefd47e90fa958fc
