### ISSUE TITLE
Non nullable names

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise-core#50]
I think we should make sure people have a real name all the time. There is no regulatory reason we'd have to not do it and it is much nicer to provide reports

https://github.com/dsi-icl/optimise-core/blob/661718596db73a9575a8f5f9eefd47e90fa958fc/db/migrations/20180621153556_users-table.js#L5

**Comment by Radiateurs** [comment]
Patched in 0b5244f7ea7c18cef09455b149c08fef2a477ee7
