### ISSUE TITLE
☢️💔 There are no real tests

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise-core#57]
@Radiateurs @sou-c 

I am quite worried about the *complete lack* of test for the API.
I was just having a look at in attempting to understand how #37 could be addressed.
Virtually every test does not perform validation. They only check of the return code of the call and not much more. This does not constitue a satisfactory testing strategy as it does not prove the calls indeed succeed and behave appropriately.

This is extremely urgent to correct !

_You should also create tests that do not rely on knex. Excellent mocking libraries exist for this._

**Comment by Radiateurs** [comment]
Will work on that with the others once the front is stable enough
