### ISSUE TITLE
Problem with seeding files

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise-core#60]
There are multiple problem with seeding files containing example data such as :

https://github.com/dsi-icl/optimise-core/blob/1dc620134a7aeb4408f0a7f7e087324cc6ca1ea4/db/seed/a_conditions.js#L4-L7

Or extra field which should not be shipped for production like: 

https://github.com/dsi-icl/optimise-core/blob/1dc620134a7aeb4408f0a7f7e087324cc6ca1ea4/db/seed/a_users.js#L4-L10

**Comment by epissari** [comment]
Issue with 'Condition' seeding file is resolved in branch `chore/dataModifications` commit ecad709549222aa550471cd455167e1c0deeff06.
