### ISSUE TITLE
URGENT get medical condition and get relations

### ISSUE THREAD

**Issue by sou-c** [dsi-icl/optimise-core#71]
when i get medical condition fields, what is returned is the relations!!! and there is no api for getting relations!!!

**Comment by Radiateurs** [comment]
See the optimise collection.
The api {url}/demographics/Fields/MedicalCondition allow you to get both the conditions AND the relations. When calling {url}/demographics/Fields/MedicalCondition?fieldName=relations you get only the relations.
When calling {url}/demographics/Fields/MedicalCondition?fieldName=conditions you get only the conditions.
Unfortunately there is currently nothing in the conditions table.
