### ISSUE TITLE
Demographic Controller : Error handling 

### ISSUE THREAD

**Issue by Radiateurs** [dsi-icl/optimise-core#8]
The error handling is very poor in the DemographicDataController and require a lot more attention for the next few days.

**Comment by Radiateurs** [comment]
[Update] Input verification improved

**Comment by fguitton** [comment]
@Radiateurs could you point us to commit numbers when you mention improvements so it's easier to review 👍

**Comment by Radiateurs** [comment]
[Update] Input Verification completed in Commit d0bb8b7ad08f95477388585836782acb92e1fb1b

**Comment by Radiateurs** [comment]
[Audit] Error in DB (see https://github.com/dsi-icl/optimise-core/issues/17 )

**Comment by Radiateurs** [comment]
Done in commit d1ccae9a8fd4d58cf03c54f6fc03999abbe281e9
