### ISSUE TITLE
NO CONTROLLER FOR MANIPULATING PII AND PRIMARY DIAGNOSIS

### ISSUE THREAD

**Issue by sou-c** [dsi-icl/optimise-core#80]
I might be wrong but I can find no api for manipulating pii and primary diagnosis
I can't do ANYTHING on the front if i don't have an api to play with 
this is URGENT!

**Comment by epissari** [comment]
PII and Diagnosis controllers in commit a39bdd870f973215a369cfda1acf95ac6d26b901
